name: 构建扩展程序

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      name: 检出代码
    
    - name: 设置 Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: 安装依赖
      run: npm install
      
    - name: 构建扩展程序
      run: npm run build
      
    - name: 上传工件
      uses: actions/upload-artifact@v3
      with:
        name: extension-build
        path: dist/