name: 构建扩展程序

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    name: 构建 Chrome 扩展程序
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      name: 检出代码
    
    - name: 设置 Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        
    - name: 安装依赖
      run: npm install
      
    - name: 构建扩展程序
      run: npm run build

    - name: 将构建结果压缩成 ZIP
      run: |-
        cd dist
        zip -r ../extension-${{ gitea.sha }}.zip ./*
        cd ..
      
    - name: 上传构建工件
      uses: actions/upload-artifact@v3
      with:
        name: extension-${{ gitea.sha }}
        path: extension-${{ gitea.sha }}.zip
  
  publish:
    name: 发布至 Chrome 应用商店
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: 下载构建工件
      uses: actions/download-artifact@v3
      with:
        name: extension-${{ gitea.sha }}
        
    - name: 设置 Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "22"

    - name: 安装 Chrome Web Store 上传工具
      run: |-
        npm install -g chrome-webstore-upload-cli

    - name: 上传扩展程序到 Chrome Web Store
      run: |-
        chrome-webstore-upload upload \
          --source extension-${{ gitea.sha }}.zip \
          --extension-id kphoaomopljjiofeaigjmbagmbdaamhh \
          --client-id ${{ secrets.CI_GOOGLE_CLIENT_ID }} \
          --client-secret ${{ secrets.CI_GOOGLE_CLIENT_SECRET }} \
          --refresh-token ${{ secrets.CI_GOOGLE_REFRESH_TOKEN }}